server:
  port: 8094
spring:
  cloud:
    gateway:
      routes:
      - id: jsonClient
        uri: http://localhost:8088
        predicates:
        - Path=/client/**
      - id: jsonProduct
        uri: http://localhost:8089
        predicates:
        - Path=/product/**
      - id: jsonProductClientCredit
        uri: http://localhost:8090
        predicates:
        - Path=/productClientCredit/**
      - id: jsonProductClientCreditCard
        uri: http://localhost:8091
        predicates:
        - Path=/productClientCreditCard/**
      - id: jsonProductClientFixed
        uri: http://localhost:8092
        predicates:
        - Path=/productClientFixed/**
      - id: jsonProductConfiguration
        uri: http://localhost:8093
        predicates:
          - Path=/productConfiguration/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
            - OPTION
          